const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined&&text!==null)n.textContent=text;if(cls)n.className=cls;return n};
const categories=[['2D DESIGN','two-d','2D DESIGN'],['3D DESIGN','three-d','3D DESIGN'],['SOCIAL MEDIA','social','SOCIAL MEDIA'],['EVENTS','events','EVENT DESIGN']];
const box=document.querySelector('#lightbox');document.querySelector('#close-image').onclick=()=>box.close();box.addEventListener('click',e=>{if(e.target===box)box.close()});
const splitLines=v=>(v||'').split('\n').filter(Boolean);
const resolveImage=src=>{
  if(typeof src!=='string') return src;
  if(src.startsWith('data:')||src.startsWith('http://')||src.startsWith('https://')||src.startsWith('blob:')) return src;
  if(src.startsWith('/uploads/')) return 'https://raw.githubusercontent.com/AhmedAl-Najjar/ahmed-alnajjar-portfolio/main/public'+src;
  return src;
};
async function render(){try{const r=await fetch('/api/content');if(!r.ok)throw Error();const d=await r.json();
document.title=d.name+' — Designer';document.querySelectorAll('[data-field]').forEach(n=>n.textContent=d[n.dataset.field]||'');document.querySelector('#year').textContent=new Date().getFullYear();
const about=document.querySelector('#about-copy');about.replaceChildren(...(d.about||'').split('\n\n').filter(Boolean).map(p=>node('p',p)));
const stats=document.querySelector('#stats');stats.replaceChildren(...(d.stats||[]).map(s=>{const x=node('div',null,'stat');x.append(node('strong',s.value),node('span',s.label));return x}));
const sg=document.querySelector('#services-grid');sg.replaceChildren(...(d.services||[]).map((s,i)=>{const x=node('article',null,'service-card');x.append(node('span',String(i+1).padStart(2,'0')),node('h3',s.title),node('p',s.description));return x}));
const pg=document.querySelector('#process-grid');pg.replaceChildren(...(d.process||[]).map(s=>{const x=node('article',null,'process-step');x.append(node('b',s.number),node('h3',s.title),node('p',s.description));return x}));
document.querySelector('#expertise').replaceChildren(...splitLines(d.expertise).map(s=>node('p',s)));
document.querySelector('#software').replaceChildren(...splitLines(d.software).map(s=>node('span',s)));
const root=document.querySelector('#projects');root.replaceChildren();for(const [cat,id,title]of categories){const items=(d.projects||[]).filter(p=>p.category===cat);if(!items.length)continue;const section=node('section');section.id=id;const cover=node('div',null,'section-cover');cover.append(node('span',cat+' / SELECTED WORK','vertical'),node('h2',title),node('span',(d.name||'').toUpperCase(),'vertical right'));section.append(cover);for(const p of items){const article=node('article',null,'project');article.style.setProperty('--accent',p.color);const meta=node('div',null,'project-meta');meta.append(node('span',p.category+' / '+p.title),node('span',p.demo?'EXPERIMENTAL':String(new Date().getFullYear())));const body=node('div',null,'project-body'),copy=node('div');copy.append(node('h3',p.title),node('p',p.description));if(p.demo)copy.append(node('span','DEMO VISUALS · REPLACEABLE','demo'));const gallery=node('div',null,'gallery');for(const [i,src]of (p.images||[]).entries()){const button=node('button');button.type='button';button.setAttribute('aria-label','View '+p.title+' image '+(i+1));const img=node('img');img.src=resolveImage(src);img.alt=p.title+' — '+(i+1);img.loading='lazy';img.addEventListener('error',()=>{button.replaceChildren(node('span','Image unavailable','image-fail'))});button.append(img);button.onclick=()=>{box.querySelector('img').src=resolveImage(src);box.querySelector('img').alt=img.alt;box.querySelector('p').textContent=p.title;box.showModal()};gallery.append(button)}body.append(copy,gallery);article.append(meta,body);section.append(article)}root.append(section)}
const links=document.querySelector('#contact-links');links.replaceChildren();for(const [key,label,prefix]of [['email','EMAIL','mailto:'],['phone','PHONE','tel:'],['behance','BEHANCE',''],['instagram','INSTAGRAM','']]){if(d[key]){const a=node('a',key==='email'?d[key]:label+' ↗');a.href=prefix+d[key];if(!prefix){a.target='_blank';a.rel='noopener noreferrer'}links.append(a)}}}
catch{document.querySelector('#projects').replaceChildren(node('p','Unable to load the portfolio. Please refresh to try again.','loading'))}}render();
